SLIDER_NAME_MAP = {
    # Primary sliders
    "temperature": "Temperature",
    "tint": "Tint",
    "exposure": "Exposure2012",
    "contrast": "Contrast2012",
    "whites": "Whites2012",
    "highlights": "Highlights2012",
    "shadows": "Shadows2012",
    "blacks": "Blacks2012",
    # Curve sliders
    "curve_highlights": "ParametricHighlights",
    "curve_lights": "ParametricLights",
    "curve_darks": "ParametricDarks",
    "curve_shadows": "ParametricShadows",
    "vibrance": "Vibrance",
    "saturation": "Saturation",
    # HSL sliders
    "hue_adjust_aqua": "HueAdjustmentAqua",
    "hue_adjust_blue": "HueAdjustmentBlue",
    "hue_adjust_green": "HueAdjustmentGreen",
    "hue_adjust_magenta": "HueAdjustmentMagenta",
    "hue_adjust_orange": "HueAdjustmentOrange",
    "hue_adjust_purple": "HueAdjustmentPurple",
    "hue_adjust_red": "HueAdjustmentRed",
    "hue_adjust_yellow": "HueAdjustmentYellow",
    "saturation_adjust_aqua": "SaturationAdjustmentAqua",
    "saturation_adjust_blue": "SaturationAdjustmentBlue",
    "saturation_adjust_green": "SaturationAdjustmentGreen",
    "saturation_adjust_magenta": "SaturationAdjustmentMagenta",
    "saturation_adjust_orange": "SaturationAdjustmentOrange",
    "saturation_adjust_purple": "SaturationAdjustmentPurple",
    "saturation_adjust_red": "SaturationAdjustmentRed",
    "saturation_adjust_yellow": "SaturationAdjustmentYellow",
    "luminance_adjust_aqua": "LuminanceAdjustmentAqua",
    "luminance_adjust_blue": "LuminanceAdjustmentBlue",
    "luminance_adjust_green": "LuminanceAdjustmentGreen",
    "luminance_adjust_magenta": "LuminanceAdjustmentMagenta",
    "luminance_adjust_orange": "LuminanceAdjustmentOrange",
    "luminance_adjust_purple": "LuminanceAdjustmentPurple",
    "luminance_adjust_red": "LuminanceAdjustmentRed",
    "luminance_adjust_yellow": "LuminanceAdjustmentYellow",
}
