services:

  train:
    profiles:
      - train
    build:
      context: .
      dockerfile: ./train/Dockerfile
    command: python train.py \
              --csv /mnt/dataset/sliders.csv \
              --previews /mnt/previews \
              --out_model /mnt/models/model.pt
    volumes:
      - ./data/previews:/mnt/previews
      - ./data/dataset:/mnt/dataset
      - ./data/models:/mnt/models
      - ./data/raw:/mnt/raw
